export default {
  ExtraLargeHeading: 28,
  LargeHeading: 26,
  Heading: 22,
  SubHeading: 20,
  text: 18,
  mediumText: 16,
  midMediumText: 15,
  intermediateMediumText: 14,
  smallText: 13,
  mediumSmallText: 12,
  midMediumSmallText: 11,
  interMidSmall: 10,
  extraSmallText: 8,
};
